global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']
    basic_auth:
      username: 'metrics'
      password_file: /run/secrets/RABBITMQ_METRICS_PASSWORD
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(rabbitmq_)?(.*)$'
        target_label: __name__
        replacement: 'rabbitmq_${2}'

  - job_name: 'metrics-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['workers-metrics:2112']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(metrics_worker_)?(.*)$'
        target_label: __name__
        replacement: 'metrics_worker_${2}'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
